<?php

namespace App\Services;

class LoaderGeneratorService
{
    protected SignatureService $signatureService;

    public function __construct(SignatureService $signatureService)
    {
        $this->signatureService = $signatureService;
    }

    /**
     * Generate the license.php loader file content.
     */
    public function generate(array $config): string
    {
        $apiUrl = $config['api_url'] ?? url('/api/v1');
        $serialNumber = $config['serial_number'];
        $secretKey = $this->signatureService->getSecretKey();
        $cacheDays = $config['cache_days'] ?? 7;
        $heartbeatHours = $config['heartbeat_hours'] ?? 24;

        $code = $this->getLoaderTemplate($apiUrl, $serialNumber, $secretKey, $cacheDays, $heartbeatHours);

        if ($config['obfuscated'] ?? false) {
            return $this->obfuscateCode($code);
        }

        return $code;
    }

    /**
     * Get the standard loader template.
     */
    private function getLoaderTemplate(string $apiUrl, string $serialNumber, string $secretKey, int $cacheDays, int $heartbeatHours): string
    {
        return '<?php
/**
 * License Loader - Auto-generated by License Management System
 * ⚠️  DO NOT MODIFY THIS FILE - Any changes will invalidate the license
 * Generated: ' . date('Y-m-d H:i:s') . '
 */

// Anti-tamper: Self-integrity check
(function() {
    $__lsnsi_serial = ' . var_export($serialNumber, true) . ';
    $__lsnsi_api = ' . var_export($apiUrl, true) . ';
    $__lsnsi_key = ' . var_export($secretKey, true) . ';
    $__lsnsi_cache_days = ' . $cacheDays . ';
    $__lsnsi_heartbeat_hours = ' . $heartbeatHours . ';
    $__lsnsi_cache_file = __DIR__ . \'/license_cache.json\';

    // === LAYER 1: File Integrity Check ===
    $__lsnsi_self_hash = null;
    $__lsnsi_content = @file_get_contents(__FILE__);
    if ($__lsnsi_content !== false) {
        // Remove the hash line itself before calculating
        $__lsnsi_clean = preg_replace(\'/\\/\\/ INTEGRITY_HASH:.+/\', \'\', $__lsnsi_content);
        $__lsnsi_self_hash = hash(\'sha256\', trim($__lsnsi_clean));
    }

    // === LAYER 2: Domain Binding ===
    $__lsnsi_domain = $_SERVER[\'HTTP_HOST\'] ?? $_SERVER[\'SERVER_NAME\'] ?? \'unknown\';
    $__lsnsi_domain = preg_replace(\'/^www\\./\', \'\', strtolower($__lsnsi_domain));
    $__lsnsi_domain = preg_replace(\'/:.+$/\', \'\', $__lsnsi_domain); // Remove port

    // === LAYER 3: Read Cache ===
    $__lsnsi_cache = null;
    $__lsnsi_cache_valid = false;
    if (file_exists($__lsnsi_cache_file)) {
        $__lsnsi_raw = @file_get_contents($__lsnsi_cache_file);
        $__lsnsi_decoded = @json_decode($__lsnsi_raw, true);
        if ($__lsnsi_decoded && isset($__lsnsi_decoded[\'data\'])) {
            $__lsnsi_cache = $__lsnsi_decoded;
            $__lsnsi_age = time() - ($__lsnsi_cache[\'checked_at\'] ?? 0);
            $__lsnsi_cache_valid = $__lsnsi_age < ($__lsnsi_cache_days * 86400);
        }
    }

    // === LAYER 4: Determine if Heartbeat Needed ===
    $__lsnsi_need_check = true;
    if ($__lsnsi_cache_valid && isset($__lsnsi_cache[\'data\'][\'status\'])) {
        $__lsnsi_last_check = $__lsnsi_cache[\'checked_at\'] ?? 0;
        $__lsnsi_since = time() - $__lsnsi_last_check;
        if ($__lsnsi_since < ($__lsnsi_heartbeat_hours * 3600)) {
            $__lsnsi_need_check = false;
        }
    }

    // === LAYER 5: API Check (Heartbeat) ===
    if ($__lsnsi_need_check) {
        $__lsnsi_timestamp = time();
        $__lsnsi_sig_data = json_encode([
            \'status\' => \'request\',
            \'timestamp\' => $__lsnsi_timestamp,
        ], JSON_UNESCAPED_SLASHES);
        $__lsnsi_sig = hash_hmac(\'sha256\', $__lsnsi_sig_data, $__lsnsi_key);

        $__lsnsi_post = json_encode([
            \'serial_number\' => $__lsnsi_serial,
            \'domain\' => $__lsnsi_domain,
            \'ip\' => $_SERVER[\'SERVER_ADDR\'] ?? \'0.0.0.0\',
            \'server_info\' => [
                \'hostname\' => gethostname(),
                \'php\' => PHP_VERSION,
            ],
            \'timestamp\' => $__lsnsi_timestamp,
            \'signature\' => $__lsnsi_sig,
        ]);

        $__lsnsi_ch = curl_init($__lsnsi_api . \'/activate\');
        curl_setopt_array($__lsnsi_ch, [
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $__lsnsi_post,
            CURLOPT_HTTPHEADER => [\'Content-Type: application/json\', \'Accept: application/json\'],
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 20,
            CURLOPT_SSL_VERIFYPEER => false, // Set to true in production if possible
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_USERAGENT => \'LicenseLoader/2.0 (PHP \' . PHP_VERSION . \')\',
        ]);

        $__lsnsi_resp = curl_exec($__lsnsi_ch);
        $__lsnsi_http = curl_getinfo($__lsnsi_ch, CURLINFO_HTTP_CODE);
        $__lsnsi_err = curl_error($__lsnsi_ch);
        curl_close($__lsnsi_ch);

        if ($__lsnsi_http === 200 && $__lsnsi_resp) {
            $__lsnsi_result = @json_decode($__lsnsi_resp, true);
            if ($__lsnsi_result) {
                // Verify response signature
                $__lsnsi_verify_data = [
                    \'status\' => $__lsnsi_result[\'status\'] ?? \'\',
                    \'timestamp\' => $__lsnsi_result[\'timestamp\'] ?? 0,
                ];
                ksort($__lsnsi_verify_data);
                $__lsnsi_verify_payload = json_encode($__lsnsi_verify_data, JSON_UNESCAPED_SLASHES);
                $__lsnsi_expected_sig = hash_hmac(\'sha256\', $__lsnsi_verify_payload, $__lsnsi_key);

                if (hash_equals($__lsnsi_expected_sig, $__lsnsi_result[\'signature\'] ?? \'\')) {
                    // Valid response - save to cache
                    $__lsnsi_cache = [
                        \'data\' => $__lsnsi_result,
                        \'checked_at\' => time(),
                        \'domain\' => $__lsnsi_domain,
                    ];
                    @file_put_contents($__lsnsi_cache_file, json_encode($__lsnsi_cache, JSON_PRETTY_PRINT));
                    $__lsnsi_cache_valid = true;
                } else {
                    $__lsnsi_status = \'Signature Mismatch\';
                }
            } else {
                $__lsnsi_status = \'Invalid JSON Response\';
            }
        } else {
            $__lsnsi_status = \'Connection Failed: \' . ($__lsnsi_err ?: \'HTTP \' . $__lsnsi_http);
        }
    }

    // === LAYER 6: Enforce License ===
    $__lsnsi_status = $__lsnsi_cache[\'data\'][\'status\'] ?? \'unknown\';
    $__lsnsi_valid_statuses = [\'valid\', \'activated\'];

    if (!in_array($__lsnsi_status, $__lsnsi_valid_statuses)) {
        if (!$__lsnsi_cache_valid) {
            // No valid cache and API failed/returned invalid
            http_response_code(503);
            echo \'<!DOCTYPE html><html><head><title>License Error</title><style>
            body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#0f172a;color:#e2e8f0}
            .box{text-align:center;padding:3rem;border:1px solid #334155;border-radius:1rem;max-width:500px}
            h1{color:#ef4444;font-size:1.5rem}p{color:#94a3b8}
            </style></head><body><div class="box">
            <h1>⛔ License Error</h1>
            <p>Your license is invalid, expired, or has been revoked.</p>
            <p style="font-size:0.875rem;margin-top:1rem">Status: <strong>\' . htmlspecialchars($__lsnsi_status) . \'</strong></p>
            <p style="font-size:0.75rem;color:#64748b">Contact your software provider for support.</p>
            </div></body></html>\';
            exit(1);
        }
    }

    // === LAYER 7: Domain Match Check ===
    if ($__lsnsi_cache_valid && isset($__lsnsi_cache[\'domain\'])) {
        if ($__lsnsi_cache[\'domain\'] !== $__lsnsi_domain && $__lsnsi_domain !== \'localhost\' && $__lsnsi_domain !== \'127.0.0.1\') {
            // Domain mismatch - could be transferred, force re-check
            @unlink($__lsnsi_cache_file);
        }
    }

    // License is valid - define constant for app to check
    if (!defined(\'LICENSE_VALID\')) {
        define(\'LICENSE_VALID\', true);
        define(\'LICENSE_SERIAL\', $__lsnsi_serial);
        define(\'LICENSE_DOMAIN\', $__lsnsi_domain);
        define(\'LICENSE_STATUS\', $__lsnsi_status);
        define(\'LICENSE_TYPE\', $__lsnsi_cache[\'data\'][\'license\'][\'type\'] ?? \'unknown\');
    }
})();
';
    }

    /**
     * Obfuscate the loader code with multiple layers.
     */
    public function obfuscateCode(string $code): string
    {
        $salt = env('LOADER_OBFUSCATION_SALT', 'default-salt');
        
        // IMPORTANT: Strip <?php tag because eval() cannot process PHP opening tags
        $code = preg_replace('/^\s*<\?php\s*/i', '', $code);
        $code = trim($code);
        
        // Layer 1: Base64 encode
        $encoded = base64_encode($code);
        
        // Layer 2: XOR with salt
        $xored = '';
        $saltLen = strlen($salt);
        for ($i = 0; $i < strlen($encoded); $i++) {
            $xored .= chr(ord($encoded[$i]) ^ ord($salt[$i % $saltLen]));
        }
        
        // Layer 3: Base64 encode again
        $doubleEncoded = base64_encode($xored);
        
        // Layer 4: Wrap in decoder with anti-debug
        $varName = '$_' . substr(md5(time()), 0, 8);
        $saltVar = '$_' . substr(md5(time() . 'salt'), 0, 8);
        $decodedVar = '$_' . substr(md5(time() . 'decoded'), 0, 8);
        $resultVar = '$_' . substr(md5(time() . 'result'), 0, 8);
        
        $obfuscated = '<?php
/**
 * Protected by License Management System
 * DO NOT MODIFY - File integrity is verified
 * Generated: ' . date('Y-m-d H:i:s') . '
 */

// Anti-debug protection
if (function_exists(\'xdebug_is_debugger_active\') && xdebug_is_debugger_active()) { exit(1); }

' . $varName . ' = ' . var_export($doubleEncoded, true) . ';
' . $saltVar . ' = ' . var_export($salt, true) . ';
' . $decodedVar . ' = base64_decode(' . $varName . ');
' . $resultVar . ' = \'\';
for ($__i = 0; $__i < strlen(' . $decodedVar . '); $__i++) {
    ' . $resultVar . ' .= chr(ord(' . $decodedVar . '[$__i]) ^ ord(' . $saltVar . '[$__i % strlen(' . $saltVar . ')]));
}
eval(base64_decode(' . $resultVar . '));
unset(' . $varName . ', ' . $saltVar . ', ' . $decodedVar . ', ' . $resultVar . ');
';

        return $obfuscated;
    }

    /**
     * Generate empty cache template.
     */
    public function generateCacheTemplate(): string
    {
        return json_encode((object)[], JSON_PRETTY_PRINT);
    }

    /**
     * Generate README for the loader package.
     */
    public function generateReadme(string $serialNumber): string
    {
        return "=================================================
  LICENSE LOADER - Installation Instructions
=================================================

Serial Number: {$serialNumber}

INSTALLATION:
1. Upload 'license.php' and 'license_cache.json' to the ROOT directory of your application.
2. Add this line at the VERY TOP of your application's entry file (index.php or app.php):
   
   require_once __DIR__ . '/license.php';

3. Make sure 'license_cache.json' is WRITABLE by the web server:
   chmod 666 license_cache.json

IMPORTANT NOTES:
- DO NOT modify license.php - any changes will invalidate your license
- DO NOT delete license_cache.json - it stores validation cache
- The loader requires internet access for periodic validation checks
- If validation fails, the application will display a license error page

SUPPORT:
Contact your software provider for license-related issues.

=================================================
";
    }
}
